/**
 * @file core.ts
 * @description Core trading types - positions, signals, trades, and orders
 */

// ============================
// Trading Position Types
// ============================

/**
 * Represents a trading position (long or short)
 */
export interface Position {
  entryPrice: number;              // Entry price of the position
  entryTime: number;               // Unix timestamp when position was opened
  size: number;                    // Position size in base asset
  type: 'long' | 'short';         // Position direction
  stopLoss?: number;              // Optional stop loss price
  takeProfit?: number;            // Optional take profit price
  metadata?: {                    // Optional strategy-specific data
    level?: number;               // For grid/ratio strategies
    reason?: string;              // Reason for opening position
    [key: string]: any;
  };
}

// ============================
// Trading Signal Types
// ============================

/**
 * Trading signal generated by strategies
 */
export interface Signal {
  type: 'buy' | 'sell' | 'hold';  // Signal action
  strength: number;               // Signal strength (0-1)
  price: number;                  // Target price
  size?: number;                  // Optional position size
  reason: string;                 // Human-readable reason
  metadata?: {                    // Optional strategy-specific data
    level?: number;
    targetPrice?: number;
    isCompleteExit?: boolean;
    totalProfit?: number;
    [key: string]: any;
  };
}

// ============================
// Trade Types
// ============================

/**
 * Trade side type
 */
export type TradeSide = 'buy' | 'sell';

/**
 * Order type
 */
export type OrderType = 'market' | 'limit' | 'stop' | 'stop-limit';

/**
 * Order status
 */
export type OrderStatus = 'pending' | 'open' | 'filled' | 'cancelled' | 'rejected';

/**
 * Executed trade record (comprehensive version)
 */
export interface Trade {
  id: string;                     // Unique trade identifier
  timestamp: number;              // Unix timestamp of execution
  type: TradeSide;                // Trade direction
  price: number;                  // Execution price
  size: number;                   // Trade size
  value: number;                  // Total trade value (price * size)
  fee?: number;                   // Trading fee paid
  grossFee?: number;              // Total fee before rebates
  feeRebate?: number;             // Fee rebate amount
  position?: Position;            // Associated position (for closes)
  profit?: number;                // Profit in USD (for closing trades)
  profitPercent?: number;         // Profit percentage
  reason: string;                 // Human-readable trade reason
  symbol?: string;                // Trading pair symbol
  orderId?: string;               // Associated order ID
  status?: OrderStatus;           // Trade status
}

/**
 * Simplified trade data for basic tracking
 * @deprecated Use Trade interface instead
 */
export interface TradeData {
  id: string;
  symbol: string;
  side: TradeSide;
  quantity: number;
  price: number;
  timestamp: string;
  fees?: number;
  orderId?: string;
  type?: OrderType;
  status?: OrderStatus;
}

// ============================
// Order Types
// ============================

/**
 * Order placed but not yet executed
 */
export interface Order {
  id: string;                     // Unique order identifier
  type: OrderType;                // Order type
  side: TradeSide;                // Order side
  price: number;                  // Order price (limit orders)
  size: number;                   // Order size
  status: OrderStatus;            // Order status
  createdAt: number;              // Creation timestamp
  filledAt?: number;              // Execution timestamp
  symbol?: string;                // Trading pair
}

// ============================
// Trading Pair Types
// ============================

/**
 * Supported trading pairs
 */
export type SupportedTradingPair =
  | 'BTC-USD' | 'ETH-USD' | 'LTC-USD' | 'BCH-USD' | 'PAXG-USD'
  | 'ADA-USD' | 'DOT-USD' | 'LINK-USD' | 'XLM-USD' | 'UNI-USD';

/**
 * Time granularities for market data
 */
export type SupportedGranularity =
  | '1m' | '5m' | '15m' | '30m' | '1h' | '2h' | '4h' | '6h' | '12h' | '1d';

/**
 * Supported strategy types
 */
export type SupportedStrategy =
  | 'reverse-descending-grid' | 'grid-trading' | 'rsi-mean-reversion'
  | 'dca' | 'vwap-bounce' | 'micro-scalping' | 'proper-scalping';
